---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-myapp-hzy-com-v1-mystate
  failurePolicy: Fail
  name: mmystate-v1.kb.io
  rules:
  - apiGroups:
    - myapp.hzy.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mystates
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-myapp-hzy-com-v1-mystate
  failurePolicy: Fail
  name: vmystate-v1.kb.io
  rules:
  - apiGroups:
    - myapp.hzy.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mystates
  sideEffects: None
