---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - myrs.github.com
  resources:
  - myreplicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - myrs.github.com
  resources:
  - myreplicasets/finalizers
  verbs:
  - update
- apiGroups:
  - myrs.github.com
  resources:
  - myreplicasets/status
  verbs:
  - get
  - patch
  - update
