apiVersion: myapp.hzy.com/v1
kind: MyState
metadata:
  name: mystate-sample
  labels:
    app.kubernetes.io/name: devops-golang-test
    app.kubernetes.io/managed-by: kustomize
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: registry.k8s.io/nginx-slim:0.24
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
